### ISSUE TITLE
ability to add db options, ex: readPreference

### ISSUE THREAD

**Issue by sb-aaron-gh** [SkeloGH/weaver#77]
**Is your feature request related to a problem? Please describe.**
Some environments will restrict read access unless a readPreference is set, preventing the tool to be usable.

**Describe the solution you'd like**
Provide a way to pass db options to a client, either during client creation or post-creation.

**Describe alternatives you've considered**
Manually editing the configuration file helps to work around the missing feature.

**Comment by SkeloGH** [comment]
For now, db options will be added during creation only, using the following syntax (--options.<option_name>):

```
Usage: weaver add client -fntou --options.<option_name>

  -f [mongodb]          <String> The client db family, mongodb is only supported for now.
  -n <name>             <String> The client db name.
  -t [source|target]    <String> source if the data will be pulled from it, target otherwise.
  -o [<source.name>]    <String> The target's origin db where the data will be copied from.
  -u <url>              <String> The client db URL.
  --options.<opt_name>  <String> Client db-specific options, for now MongoClient options, use dot notation to set each option
                        Example: --options.readPreference secondaryPreferred
```
